function VWMlearningego = import_log_files(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   VWMLEARNINGEGO = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   VWMLEARNINGEGO = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   VWMlearningego = importfile('16_1_VWM_learning ego.log', 1, 336);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/06/11 09:45:17

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%s%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
VWMlearningego = table;
VWMlearningego.trial_ID = dataArray{:, 1};
VWMlearningego.trial_Name = cellstr(dataArray{:, 2});
VWMlearningego.event_type = cellstr(dataArray{:, 3});
VWMlearningego.sync_onset = dataArray{:, 4};
VWMlearningego.x_coord = dataArray{:, 5};
VWMlearningego.y_coord = dataArray{:, 6};
VWMlearningego.distance_moved_1 = dataArray{:, 7};
VWMlearningego.distance_moved_2 = dataArray{:, 8};

